apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.config.name }}
  namespace: {{ .Release.Namespace }}
data:
  DB_HOST: "{{ .Values.db.service.name }}"
  DB_PORT: "{{ .Values.db.service.port }}"