apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.liveService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.app.testService.type }}
  selector:
    {{ include "liveAppLabels" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.testService.port }}
      targetPort: {{ .Values.app.testService.targetPort }}
      {{- if eq .Values.app.testService.type "NodePort" }}
      {{- end }}
