apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.db.secret.data.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.db.secret.data.POSTGRES_USER | b64enc }}
  POSTGRES_DB: {{ .Values.db.secret.data.POSTGRES_DB | b64enc }}
  PGDATA: {{ .Values.db.secret.data.PGDATA | b64enc }}