apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgres
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}
