apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: web-app
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
