apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: web-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded value of "postgres"
  POSTGRES_PASSWORD: c2VjcmV0UGFzc3dvcmQxIQ== # base64 encoded value of "secretPassword1!"
  POSTGRES_DB: d2ViYXBw # base64 encoded value of "webapp"