liveColor: blue
testColor: green

app:
  config:
    name: app-config
  secret:
    name: app-secret
    data:
      SECRET_KEY: <your-app-secret>
  greenDeployment:
    name: app-deployment-green
    replicas: 1
    image:
      repository: turb0bur/fastapi-crud
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1"
  blueDeployment:
    name: app-deployment-blue
    replicas: 0
    image:
      repository: turb0bur/fastapi-crud
      tag: latest
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1"
  testService:
    name: app-service-test
    type: LoadBalancer
    port: 5000
    targetPort: 5000
    nodePort: 30080
  liveService:
    name: app-service-live
    type: LoadBalancer
    port: 5000
    targetPort: 5000
    nodePort: 30081

db:
  secret:
    name: postgres-secret
    data:
      POSTGRES_DB: webapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <your-db-password>
      PGDATA: /var/lib/postgresql/data/pgdata
  statefulset:
    name: postgres-statefulset
    serviceName: postgres-service
    replicas: 1
    port: 5432
    storage: 1Gi
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"
  service:
    name: postgres-service
    type: ClusterIP
    port: 5432
    targetPort: 5432
